DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

  submit_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  started_time TIMESTAMP WITH TIME ZONE,
  estimated_time TIMESTAMP WITH TIME ZONE,
  completed_time TIMESTAMP WITH TIME ZONE,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  note TEXT,
  tax NUMERIC(5, 2),
  tip NUMERIC(5, 2),
  discount NUMERIC(5, 2)
);
