DROP TABLE IF EXISTS order_details CASCADE;

CREATE TABLE order_details (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  quantity SMALLINT NOT NULL DEFAULT 1,
  price NUMERIC(5, 2) NOT NULL,
  note TEXT,
  discount_id INTEGER REFERENCES discounts(id) ON DELETE CASCADE
);
